name: mini_catalog_app
description: >
  Flutter Günlük Eğitim projesi için hazırlanmış
  basit bir Mini Katalog Uygulaması.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Ekstra paket yok (eğitim kapsamı gereği)

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/products.json
